{% set maturin_version = ">=1.8.2,<2" %}
{% set maturin_version = ">=1.8.2,<2" %}
{% set maturin_version = ">=1.8.2,<2" %}
{% set maturin_version = ">=1.8.2,<2" %}
{% set maturin_version = ">=1.8.2,<2" %}
{% set maturin_version = ">=1.8.2,<2" %}
{% set version = "0.12.43" %}

package:
  name: pycrdt
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pycrdt/pycrdt-{{ version }}.tar.gz
  sha256: 32cb97f8e75ca8e5612985a2185514c61cdb4c166a9e0ebb8a9b602d5709f0a3

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - python
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin
  host:
    - maturin
    - pip
    - python
  run:
    - python
    - anyio >=4.4.0,<5.0.0
    - typing_extensions >=4.14.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pycrdt
    - pycrdt._awareness
    - pycrdt._doc
    - pycrdt._text
    - pycrdt._array
    - pycrdt._map
    - pycrdt._transaction
    - pycrdt._undo
    - pycrdt._update
    - pycrdt._sync

about:
  home: https://github.com/y-crdt/pycrdt
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CRDTs based on Yrs
  dev_url: https://github.com/y-crdt/pycrdt
  doc_url: https://y-crdt.github.io/pycrdt

extra:
  recipe-maintainers:
    - davidbrochart
