{% set maturin_version = ">=1.8.2,<2" %}
{% set maturin_version = ">=1.8.2,<2" %}
{% set maturin_version = ">=1.8.2,<2" %}
{% set maturin_version = ">=1.8.2,<2" %}
{% set maturin_version = ">=1.8.2,<2" %}
{% set version = "0.12.13" %}

package:
  name: pycrdt
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pycrdt/pycrdt-{{ version }}.tar.gz
  sha256: dbf1d4785a25f614b057a1d7c66539bcd6ee4cd5aaa00c93f1f2ac5d0ae1f9c3

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - python
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin
  host:
    - maturin
    - pip
    - python
  run:
    - python
    - anyio >=4.4.0,<5.0.0
    - importlib_metadata >=3.6

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pycrdt
    - pycrdt._awareness
    - pycrdt._doc
    - pycrdt._text
    - pycrdt._array
    - pycrdt._map
    - pycrdt._transaction
    - pycrdt._undo
    - pycrdt._update
    - pycrdt._sync

about:
  home: https://github.com/jupyter-server/pycrdt
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CRDTs based on Yrs
  dev_url: https://github.com/jupyter-server/pycrdt
  doc_url: https://jupyter-server.github.io/pycrdt

extra:
  recipe-maintainers:
    - davidbrochart
